spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:C:/Users/Hubert/Desktop/Studia/Sem_3/BDBT/athletics-club'
  jpa:
    hibernate:
      ddl-auto: update
