


spring:
  datasource:
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:athletics-club'
  h2:
    console:
      enabled: true
      path: '/h2-console'
  jpa:
    hibernate:
      ddl-auto: create