
spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/dtrza/Desktop/athletics-club/athletics-club-db'
  jpa:
    hibernate:
      ddl-auto: validate
